# Generated by Django 3.0.2 on 2020-11-12 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, null=True)),
                ('lastname', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lga_name', models.CharField(max_length=50, null=True)),
                ('lga_description', models.TextField()),
                ('date_entered', models.DateField(auto_now_add=True, null=True)),
                ('user_ip_address', models.CharField(max_length=50, null=True)),
                ('entered_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bincom.AgentDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(choices=[('PDP', 'PDP'), ('DPP', 'DPP'), ('ACN', 'ACN'), ('PPA', 'PPA'), ('CDC', 'CDC'), ('JP', 'JP'), ('ANPP', 'ANPP'), ('LABOUR', 'LABOUR'), ('CPP', 'CPP')], default='PDP', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=50, null=True)),
                ('polling_unit_name', models.CharField(max_length=50, null=True)),
                ('party_score', models.IntegerField(verbose_name=11)),
                ('ward_description', models.CharField(max_length=255, null=True)),
                ('date_entered', models.DateField(auto_now_add=True, null=True)),
                ('user_ip_address', models.CharField(max_length=50, null=True)),
                ('entered_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_agent_details', to='bincom.AgentDetails')),
                ('lga_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_lga_id', to='bincom.Lga')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Polling_unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_unit_name', models.CharField(max_length=50, null=True)),
                ('party_score', models.IntegerField(verbose_name=11)),
                ('polling_unit_description', models.TextField(max_length=255, null=True)),
                ('date_entered', models.DateField(auto_now_add=True, null=True)),
                ('lat', models.CharField(max_length=255, null=True)),
                ('lng', models.CharField(max_length=255, null=True)),
                ('user_ip_address', models.CharField(max_length=50, null=True)),
                ('entered_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_unit_agents', to='bincom.AgentDetails')),
                ('lga_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_units_lga', to='bincom.Lga')),
                ('ward_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_units_wards', to='bincom.Ward')),
            ],
        ),
        migrations.AddField(
            model_name='lga',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bincom.States'),
        ),
        migrations.CreateModel(
            name='Announced_ward_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=50, null=True)),
                ('party_abbreviation', models.CharField(max_length=4, null=True)),
                ('party_score', models.IntegerField(verbose_name=11)),
                ('date_entered', models.DateField(auto_now_add=True, null=True)),
                ('user_ip_address', models.CharField(max_length=50, null=True)),
                ('entered_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_result', to='bincom.AgentDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Announced_state_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50, null=True)),
                ('party_abbreviation', models.CharField(max_length=4, null=True)),
                ('party_score', models.IntegerField(verbose_name=11)),
                ('date_entered', models.DateField(auto_now_add=True, null=True)),
                ('user_ip_address', models.CharField(max_length=50, null=True)),
                ('entered_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_result', to='bincom.AgentDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Announced_pu_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lga_name', models.CharField(max_length=50, null=True)),
                ('party_abbreviation', models.CharField(max_length=4, null=True)),
                ('party_score', models.IntegerField(verbose_name=11)),
                ('date_entered', models.DateField(auto_now_add=True, null=True)),
                ('user_ip_address', models.CharField(max_length=50, null=True)),
                ('entered_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bincom.AgentDetails')),
                ('polling_unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_unit_result', to='bincom.Polling_unit')),
            ],
        ),
        migrations.CreateModel(
            name='Announced_lga_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lga_name', models.CharField(max_length=50, null=True)),
                ('party_abbreviation', models.CharField(max_length=4, null=True)),
                ('party_score', models.IntegerField(verbose_name=11)),
                ('date_entered', models.DateField(auto_now_add=True, null=True)),
                ('user_ip_address', models.CharField(max_length=50, null=True)),
                ('entered_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bincom.AgentDetails')),
            ],
        ),
        migrations.AddField(
            model_name='agentdetails',
            name='polling_unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_unit', to='bincom.Polling_unit'),
        ),
        migrations.AddField(
            model_name='agentdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
