# Generated by Django 3.0.2 on 2020-11-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bincom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling_unit',
            name='polling_unit_name',
            field=models.CharField(choices=[('SAPALE WARD', 'SAPALE WARD'), ('PRIMARY SCHOOL AGHARA', 'PRIMARY SCHOOL AGHARA'), ('ISHERE PRIMARY SCHOOL', 'ISHERE PRIMARY SCHOOL'), ('CHURCH IN EFFURUNI OVWEI ', 'CHURCH IN EFFURUNI OVWEI '), ('SCHOOL ETHIOPE WEST', 'SCHOOL ETHIOPE WEST'), ('OKEGBE QUARTERS', 'OKEGBE QUARTERS'), ('EMAMI QUARTERS', 'EMAMI QUARTERS'), ('OBITEOGBON QUARTERS', 'OBITEOGBON QUARTERS'), ('IGINI PRIMARY SCHOOL', 'IGINI PRIMARY SCHOOL')], default='SAPALE WARD', max_length=255),
        ),
    ]
