# Generated by Django 3.0.2 on 2020-11-12 09:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bincom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentDetails',
            new_name='AgentDetail',
        ),
        migrations.RenameModel(
            old_name='Announced_lga_results',
            new_name='Announced_lga_result',
        ),
        migrations.RenameModel(
            old_name='Announced_pu_results',
            new_name='Announced_pu_result',
        ),
        migrations.RenameModel(
            old_name='States',
            new_name='State',
        ),
    ]
