# Generated by Django 3.1.1 on 2020-11-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bincom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announced_lga_result',
            name='party_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='announced_pu_result',
            name='party_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='announced_ward_result',
            name='party_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='polling_unit',
            name='party_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ward',
            name='party_score',
            field=models.IntegerField(),
        ),
    ]
