# Generated by Django 3.0.2 on 2020-11-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bincom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='user',
        ),
    ]
