# Generated by Django 3.0.2 on 2020-11-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bincom', '0002_remove_ward_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ward',
            old_name='polling_unit_id',
            new_name='polling_unit',
        ),
    ]
