# Generated by Django 3.1.1 on 2020-11-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bincom', '0002_auto_20201112_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentdetail',
            name='polling_unit_id',
        ),
    ]
