# Generated by Django 3.0.2 on 2020-11-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bincom', '0004_polling_unit_lga_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lga',
            name='lga_name',
            field=models.CharField(max_length=50),
        ),
    ]
