# Generated by Django 3.0.2 on 2020-11-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bincom', '0007_auto_20201122_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='party_score',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='polling_unit_name',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='user_ip_address',
        ),
    ]
